#!/bin/bash

function cleanup() {
  sed '
  s/<hasQualifier>[^<]*<\/hasQualifier>//g; 
  s/<[^>]*>/|/g; 
  s/&gt;/>/g; 
  s/&lt;/</g; 
  s/&amp;/&/g; 
  s/&quot;//g; 
  s/&apos/\;/g; 
  s/| *|/|/g;
  s/| *|/|/g;
  s/| *|/|/g;
  s/| *|/|/g;
  s/| *|/|/g;
  s/\t|/\t/g;
  s/|\t/\t/g;
  s/|$//g;
  ' ;
}

host="$1"
if [ "$host" = "" ]; then
	host="127.0.0.1"
fi
db_name="cms"
MYSQL="mysql -h cms-db2 -uroot $db_name -e"

query="select media_category, count(*) as 'Total Products' from PRODUCT_AV_MEDIA group by media_category"
$MYSQL "$query" | cleanup > /tmp/avmStats.csv
echo "" >> /tmp/avmStats.csv

query="select media_category, count(*) as 'Desc NULL' from PRODUCT_AV_MEDIA where brief_description is null group by media_category"
$MYSQL "$query" | cleanup >> /tmp/avmStats.csv
echo "" >> /tmp/avmStats.csv

query="select pam.media_category, count(*) as 'Image Not NULL' from PRODUCT_AV_MEDIA pam, IMAGE_UPLOADS iu where pam.product_id=iu.product_id group by pam.media_category"
$MYSQL "$query" | cleanup >> /tmp/avmStats.csv
echo "" >> /tmp/avmStats.csv
 
query="select pam.media_category, count(*) as 'Qualifier NULL' from PRODUCT_EAV_TABLE peav, PRODUCT_AV_MEDIA pam where peav.product_id=pam.product_id and peav.attr_name='contributor' and peav.attr_qualifier is null group by pam.media_category"
$MYSQL "$query" | cleanup >> /tmp/avmStats.csv
echo "" >> /tmp/avmStats.csv

query="select pam.media_category, ps.shipping_days , count(*) as 'Total Products' from PRODUCT_STOCKS ps, PRODUCT_AV_MEDIA pam where pam.product_id=ps.product_id group by pam.media_category , ps.shipping_days"
$MYSQL "$query" | cleanup >> /tmp/avmStats.csv
echo "" >> /tmp/avmStats.csv

date|mutt -a /tmp/avmStats.csv -s "AV_MEDIA Data Density Status" ankit@flipkart.com,aagarwal@flipkart.com,abhishekm@flipkart.com


