#!/bin/bash
cat="$1"
host="$2"
if [ "$host" = "" ]; then
	host="localhost"
fi
if [ "$cat" = "" ]; then
	echo "catp [avm|mob|com|]"
	exit 0;
fi
db_name="cms"

MYSQL="mysql -h $host -uroot $db_name -e"
echo "Usage: catp [avm|mob|com] [hostname] | count on $host"

src="PRODUCT_COMPUTER" 
echo "$src($cat)" : `$MYSQL "select count(*) from $src"`
src="SUPPLIER_COMPUTER" 
echo "$src($cat)" : `$MYSQL "select count(*) from $src"`
echo ""

src="PRODUCT_PRICING" 
echo "$src($cat)" : `$MYSQL "select count(distinct product_id) from $src where product_id like '$cat%'"`
src="SUPPLIER_PRICING" 
echo "$src($cat)" : `$MYSQL "select count(distinct product_id) from $src where product_id like '$cat%'"`
echo ""

src="PRODUCT_STOCKS" 
echo "$src($cat)" : `$MYSQL "select count(distinct product_id) from $src where product_id like '$cat%'"`
src="SUPPLIER_STOCKS" 
echo "$src($cat)" : `$MYSQL "select count(distinct product_id) from $src where product_id like '$cat%'"`



