#!/bin/bash
reportData() {
	category="";
	db_name="cms_metrics"
	MYSQL="/usr/bin/mysql -uroot $db_name -e"

	if [ "$1" = "avm" ]; then
		category="AV_MEDIA"
	fi
	if [ "$1" = "mob" ]; then
		category="MOBILE"
	fi
	if [ "$1" = "acc" ]; then
		category="ACCESSORY"
	fi
	if [ "$1" = "gmc" ]; then
		category="GAMING_CONSOLE"
	fi

	completenessTable=$category"_COMPLETENESS";
	availabilityTable=$category"_AVAILABILITY"
	discountTable=$category"_DISCOUNT";
	slaTable=$category"_SLA";
	adsTable=$category"_ATTRIBUTE_DISCOUNT_SLA";

	productTable="PRODUCT_"$category;

	#echo $completenessTable $availabilityTable $discountTable $slaTable $adsTable $productTable
	#echo "inserting into $completenessTable for $cat"
	query="insert into $completenessTable (attr_name, products, percentage, total, reported_on) (select attr_name, count(*) as products, floor(count(*)/(select count(*) from cms.$productTable)*100) as percentage, ((select count(*) from cms.$productTable)) as total, CURRENT_DATE() as reported_on from cms.PRODUCT_EAV_TABLE where product_id like '$cat%' group by attr_name)"
$MYSQL "$query"

	#echo "inserting into $availabilityTable for $cat"
	query="insert into $availabilityTable (available, percentage, total, reported_on) (select count(*) as available, floor(count(*)/(select count(*) from cms.$productTable)*100) as percentage, ((select count(*) from cms.$productTable)) as total, CURRENT_DATE as reported_on from cms.PRODUCT_STOCKS where is_available=1 and product_id like '$cat%')"
	$MYSQL "$query"

	#echo "inserting into $discountTable for $cat"
	query="insert into $discountTable (discount, avg_sla, products, reported_on) (select floor((mrp-fk_price)/mrp*100/5)*5 as discount, AVG(shipping_days) as avg_sla, count(*) as products, CURRENT_DATE as reported_on from cms.PRODUCT_STOCKS where is_available=1 and product_id like '$cat%' group by discount)"
	$MYSQL "$query"

	#echo "inserting into $slaTable for $cat"
	query="insert into $slaTable (sla, avg_discount, products, reported_on) (select shipping_days as sla, AVG((mrp-fk_price)/mrp)*100 as avg_discount, count(*) as products, CURRENT_DATE as reported_on from cms.PRODUCT_STOCKS where is_available=1 and product_id like '$cat%' group by sla)"
	$MYSQL "$query"

	#echo "inserting into $adsTable for $cat"
	query="insert into $adsTable (attr_name, avg_discount, avg_sla, reported_on) (select attr_name, AVG((mrp-fk_price)/mrp)*100 as avg_discount, AVG(shipping_days) as avg_sla, CURRENT_DATE as reported_on from cms.PRODUCT_EAV_TABLE pet, cms.PRODUCT_STOCKS ps where ps.product_id like '$cat%' and ps.product_id=pet.product_id and is_available=1 group by attr_name)"
	$MYSQL "$query"
}

categories=(avm mob acc gmc)
for cat in "${categories[@]}"; do
	#echo "reporting data for $cat"
	reportData $cat
done

#cat="$1"
#if [ "$cat" = "" ]; then
#	echo "Usage: cmsMetricsCron [avm|mob|acc|gmc]";
#	exit 0;
#fi



