#!/bin/bash
trim() { echo $1; }

MYSQL=/usr/bin/mysql
db_name="cms"
groupDupPids="$1"
if [ "$groupDupPids" = "" ]; then
	echo "Usage: deleteDuplicatePid groupDupPids.txt";
	exit 0;
fi

deleteFromTables=(SUPPLIER_PRODUCT_IDENTIFICATION)
exec<$groupDupPids
while IFS=',' read -ra pids; do
	for (( i = 1 ; i < ${#pids[@]} ; i++ )); do
		keepPid=${pids[0]}
		keepPid="$(trim $keepPid)"
		pid=${pids[$i]}
		pid="$(trim $pid)"
		for table in "${deleteFromTables[@]}"; do
			query="update $table set product_id='$keepPid' where product_id='$pid'"
			$MYSQL -N -uroot $db_name -e "$query"
		done
		query="replace into DUPLICATE_PRODUCTS (product_id,duplicate_id) values ('$keepPid','$pid')"
		$MYSQL -N -uroot $db_name -e "$query"
		deleteUrl="http://localhost:9090/solr/update?stream.body=<delete><id>$pid</id></delete>"
		curl $deleteUrl >> /tmp/solrDelete.txt
	done
done
commitUrl="http://localhost:9090/solr/update?stream.body=<commit/>"
curl $commitUrl
query="select count(*) from DUPLICATE_PRODUCTS"
$MYSQL -N -uroot $db_name -e "$query"

