#!/bin/bash

if [ "$1" = "" ]; then
	echo "Usage: dft [itf|mf|inf] AVMCNQ5XGHXXNEYB";
	exit 0;
fi
if [ "$2" = "" ]; then
	echo "Usage: dft [itf|mf|inf] AVMCNQ5XGHXXNEYB";
	exit 0;
fi

src=""

if [ "$1" = "inf" ]; then
	src="CMS_INDEXING_FAILURES"
fi

if [ "$1" = "itf" ]; then
	src="CMS_ITEMIZATION_FAILURES"
fi

if [ "$1" = "mf" ]; then
	src="CMS_MERGE_FAILURES"
fi

db_name="cms"
plist="("
for pid in $@
	do
		plist="$plist'$pid',"
	done
len=`echo ${#plist}`
plist=${plist:0:len-1} 
plist="$plist)"
query="delete from $src where product_id in $plist"
echo $query
mysql -uroot $db_name -e "$query"



