#!/bin/bash
if [ "$1" = "" ]; then
	echo "Usage: dp AVMCNZKKFQAGYQW2";
	exit 0;
fi
db_name="cms"
plist="("
for pid in $@
	do
	plist="$plist'$pid',"
	done
len=`echo ${#plist}`
plist=${plist:0:len-1} 
plist="$plist)"
query="select product_id, duplicate_id, last_modified from DUPLICATE_PRODUCTS where duplicate_id in $plist"
echo $query
mysql -uroot $db_name -e "$query" 


