#!/bin/bash
shopt -s expand_aliases
source ~/bhim/scripts/bashrc.bhim.sh

domain="$1"
if [ "$1" = "" ];  then
	domain="PROD"
fi

if [ "$domain" = "all" ]; then
	sudo rabbitmqctl list_queues | grep -v SLQ
else
	sudo rabbitmqctl list_queues | grep -i $domain | grep -v SLQ
fi

