#!/bin/bash

if [ "$1" = "" ]; then
	echo "Usage: pfail [inf|itf|mf] 20 [avm|com]";
	exit 0;
fi

src=""
cat="$3"

if [ "$1" = "inf" ]; then
	src="CMS_INDEXING_FAILURES"
fi

if [ "$1" = "itf" ]; then
	src="CMS_ITEMIZATION_FAILURES"
fi

if [ "$1" = "mf" ]; then
	src="CMS_MERGE_FAILURES"
fi

limit="$2"
if [ "$limit" = "" ]; then
	limit=10
fi

db_name="cms"
query="select product_id, product_name, media_format, media_category, media_edition, language, release_year from PRODUCT_AV_MEDIA where product_id in (select distinct product_id from $src where product_id like 'avm%')"
echo $query
mysql -uroot $db_name -e "$query"



