#!/bin/bash
db_name="cms"
plist="("
for pid in $@
	do
	plist="$plist'$pid',"
	done
len=`echo ${#plist}`
plist=${plist:0:len-1} 
plist="$plist)"
query="select item_id, product_id, last_modified, created_on from PRODUCT_ITEMS where product_id in $plist"
echo $query
mysql -uroot $db_name -e "$query" 


