#!/bin/bash
db_name="cms"
if [ "$1" = "" ]; then
	echo "Usage: pm MOBCZW3DZH8ZR5X8";
	exit 0;
fi
plist="("
for pid in $@
	do
	plist="$plist'$pid',"
	done
len=`echo ${#plist}`
plist=${plist:0:len-1} 
plist="$plist)"
#echo $plist
query="select product_id, brand, model_id, variant, color from PRODUCT_MOBILE where product_id in $plist"
echo $query
mysql -uroot $db_name -e "$query"


