#!/bin/bash
db_name="cms"
if [ "$1" = "" ]; then
	echo "Usage: pn VPCEB36FG/W";
	exit 0;
fi
plist="("
for pid in $@
	do
	plist="$plist'$pid',"
	done
len=`echo ${#plist}`
plist=${plist:0:len-1} 
plist="$plist)"
#echo $plist
query="select pc.product_id, pc.brand, pc.model_id, peav.attr_value as part_number from PRODUCT_COMPUTER pc, PRODUCT_EAV_TABLE peav where pc.product_id=peav.product_id and peav.attr_name='part_number' and peav.attr_value in $plist"
echo $query
mysql -h cms-db2.nm.flipkart.com -uroot $db_name -e "$query"


