#!/bin/bash
pc="$1"
cat="$2"
pcs=""
if [ "$pc" = "" ]; then
	echo "pppc [fps] [avm|mob|com]"
	exit 0;
fi
if [ "$pc" = "fps" ]; then
	pcs="flipkart_selling_price"
fi
db_name="cms"

MYSQL="mysql -uroot $db_name -e"
echo "Usage: pppc [fsp] [avm|mob|com]"

src="PRODUCT_PRICING"
query="select product_id, price_component, component_value, last_modified from $src where price_component='$pcs'"
echo $query
mysql -uroot $db_name -e "$query"


