#!/bin/bash
db_name="cms"
plist="("
if [ "$1" = "" ]; then
	echo "Usage: prb AVMCZW3DZH8ZR5X8";
	exit 0;
fi
for pid in $@
	do
	plist="$plist'$pid',"
	done
len=`echo ${#plist}`
plist=${plist:0:len-1} 
plist="$plist)"
query="select product_id, title, binding, language, edition, publisher, year from PRODUCT_REGIONAL_BOOKS where product_id in $plist"
echo $query
mysql -uroot $db_name -e "$query"



