#!/bin/bash
trim() { echo $1; }

db_name="cms"
groupDupPids="$1"
if [ "$groupDupPids" = "" ]; then
	echo "Usage: replacePid groupDupPids.txt";
	exit 0;
fi

updateTables=(SUPPLIER_AV_MEDIA SUPPLIER_EAV_TABLE SUPPLIER_PRICING SUPPLIER_PRODUCT_IDENTIFICATION SUPPLIER_STOCKS)
exec<$groupDupPids
while IFS=',' read -ra pids; do
	for (( i = 1 ; i < ${#pids[@]} ; i++ )); do
		keepPid=${pids[0]}
		keepPid="$(trim $keepPid)"
		pid=${pids[$i]}
		pid="$(trim $pid)"
		#echo "keep |$keepPid| for |$pid|"
		for table in "${updateTables[@]}"; do
			#echo "updating in $table..."
			query="update $table set product_id='$keepPid' where product_id='$pid'"
			echo $query
			mysql -N -uroot $db_name -e "$query"
		done
	done
done


