#!/bin/bash
db_name="cms"
plist="("
if [ "$1" = "" ]; then
	echo "Usage: sam AVMCZW3DZH8ZR5X8";
	exit 0;
fi
for pid in $@
	do
	plist="$plist'$pid',"
	done
len=`echo ${#plist}`
plist=${plist:0:len-1} 
plist="$plist)"
query="select product_id, supplier_id, product_name, media_format, media_category, media_edition, language, release_year from SUPPLIER_AV_MEDIA where product_id in $plist"
echo $query
mysql -uroot $db_name -e "$query"



