#!/bin/bash
db_name="cms"
plist="("
if [ "$1" = "" ]; then
	echo "Usage: sp AVMCZW3DZH8ZR5X8";
	exit 0;
fi
for pid in $@
	do
	plist="$plist'$pid',"
	done
len=`echo ${#plist}`
plist=${plist:0:len-1} 
plist="$plist)"
query="select product_id, supplier_id, price_component, component_value, last_modified from SUPPLIER_PRICING where price_component='flipkart_selling_price' and product_id in $plist"
echo $query
mysql -uroot $db_name -e "$query"



