#!/bin/bash
db_name="cms"
plist="("
if [ "$1" = "" ]; then
	echo "Usage: spi AVMCZW3DZH8ZR5X8";
	exit 0;
fi
for pid in $@
	do
	plist="$plist'$pid',"
	done
len=`echo ${#plist}`
plist=${plist:0:len-1} 
plist="$plist)"
query="select product_id, supplier_id, last_modified, supplier_item_id from SUPPLIER_PRODUCT_IDENTIFICATION where product_id in $plist"
echo $query
mysql -uroot $db_name -e "$query"



