#!/bin/bash
db_name=$1

echo "Truncating ALL tables in $db_name"
echo "------------------------------------------"

for table_name in `showTables $db_name -sss`
do
	truncateTable $db_name $table_name
done

