#!/bin/bash
shopt -s expand_aliases
source ~/bhim/configs/bashrc.bhim.sh
#set -x
#set -e

base=""

if [ "$1" = "cms" ] 
then
	base="/opt/tomcat/"
elif [ "$1" = "solr" ]
then
	base="/opt/tomcat_solr/"
elif [ "$1" = "service" ]
then
	base="/opt/tomcat_cms-service"
fi

if [ "$base" = "" ] 
then
	return;
fi

clearFolder $base/logs
/bin/rm -rf $base/catalina.pid
#$base/bin/catalina.sh $2 start
$base/bin/startup.sh
sleep 5
#/usr/bin/less -nM $base/logs/catalina.out
pgt

