#!/bin/bash
#for i in tomcat tomcat_solr tomcat_cms-service
shopt -s expand_aliases
source ~/bhim/configs/bashrc.bhim.sh
#set -x
#for i in tomcat tomcat_solr 
for i in cms solr 
do
	~/bin/stopTomcat $i
	#/opt/$i/bin/catalina.sh stop -force
	#sleep 5
done
pgt
