#!/bin/bash
shopt -s expand_aliases
source ~/bhim/configs/bashrc.bhim.sh
#set -x
#set -e

base=""

if [ "$1" = "cms" ] 
then
	base="/opt/tomcat/"
elif [ "$1" = "solr" ]
then
	base="/opt/tomcat_solr/"
elif [ "$1" = "service" ]
then
	base="/opt/tomcat_cms-service"
fi

if [ "$base" = "" ] 
then
	return;
fi
#$base/bin/catalina.sh stop -force
$base/bin/shutdown.sh
sleep 5
pgt

